apiVersion: v1
kind: PersistentVolume
metadata:
  name: slicevolume
spec:
  capacity:
    storage: "100Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slicevolumeclaim
spec:
  resources:
    requests:
      storage: "50Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slice-db-deployment
  labels:
    app: slice-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slice-db
  template:
    metadata:
      labels:
        app: slice-db
    spec:
      volumes:
        - name: data
          persistentVolumeClaim: 
            claimName: slicevolumeclaim
      containers:
      - name: slice-db
        image: slicedb/slice-db:v1
        volumeMounts:
          - mountPath: "/app/backup"
            name: data
        env:
          - name: "HOST"
            value: "0.0.0.0"
          - name: "PORT"
            value: "6379"
          - name: ENABLE_PERSISTENCE
            value: "True"
          - name: WAL_FILE_PATH
            value: "/app/backup/aof.slice"
          - name: "FLUSH_FREQUENCY"
            value: "1"
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: slice-db-service
spec:
  selector:
    app.kubernetes.io/name: slice-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379