from core.commandhandler.command_handler import CommandHandler
from core.commandhandler.string_command_handler import StringCommandHandler
from core.commandhandler.supported_commands import SupportedCommands